[package]
name = "spica-ebpf"
version = "0.1.0"
edition.workspace = true

[dependencies]
spica-common = { path = "../spica-common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "spica"
path = "src/main.rs"
